# Generated by Django 4.2.7 on 2025-07-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadsubscription',
            name='subscription',
            field=models.BooleanField(default=False),
        ),
    ]
